export const groupMarkers = [
  {
    title: '홍대 개미',
    writer: '작성자',
    date: '2023-10-1',
    fav: true,
    latitude: 0,
    longitude: 1,
    groupId: 1,
    groupTitle: '홍삼',
  },
  {
    title: '피오니',
    writer: '작성자',
    date: '2023-10-2',
    fav: true,
    latitude: 0,
    longitude: 1,
    groupId: 1,
    groupTitle: '홍삼',
  },
  {
    title: '탕후루',
    writer: '작성자',
    date: '2023-10-3',
    fav: true,
    latitude: 0,
    longitude: 1,
    groupId: 2,
    groupTitle: '친구',
  },
  {
    title: '현우동',
    writer: '작성자',
    date: '2023-10-4',
    fav: true,
    latitude: 0,
    longitude: 1,
    groupId: 2,
    groupTitle: '친구',
  },
  {
    title: '슈붕 파는 곳',
    writer: '작성자',
    date: '2023-10-5',
    fav: true,
    latitude: 0,
    longitude: 1,
    groupId: 3,
    groupTitle: '가족',
  },
  {
    title: '파주 영어마을',
    writer: '작성자',
    date: '2023-10-5',
    fav: true,
    latitude: 0,
    longitude: 1,
    groupId: 3,
    groupTitle: '가족',
  },
  {
    title: '파주 영어마을',
    writer: '작성자',
    date: '2023-10-5',
    fav: true,
    latitude: 0,
    longitude: 1,
    groupId: 3,
    groupTitle: '가족',
  },
  {
    title: '파주 영어마을',
    writer: '작성자',
    date: '2023-10-5',
    fav: true,
    latitude: 0,
    longitude: 1,
    groupId: 3,
    groupTitle: '가족',
  },
];

export const groups = [
  { groupId: 1, groupTitle: '홍삼' },
  { groupId: 2, groupTitle: '친구' },
  { groupId: 3, groupTitle: '가족' },
];
